---
title: "Simulation 1db: One Iteration cross-sectional and Heteroskedasticity"
output:
  html_document:
    df_print: paged
---



```{r,warning=FALSE,message=FALSE}
if(!require(mvtnorm)){install.packages("mvtnorm");library(mvtnorm)}else{library(mvtnorm)}
if(!require(quantreg)){install.packages("quantreg");library(quantreg)}else{library(quantreg)}
if(!require(MASS)){install.packages("MASS");library(MASS)}else{library(MASS)}
if(!require(foreach)){install.packages("foreach");library(foreach)}else{library(foreach)}
if(!require(tidyverse)){install.packages("tidyverse");library(tidyverse)}else{library(tidyverse)}
#self-made functions
source("./functions/qsicm.R")
source("./functions/plrq.R")
source("./functions/utils.R")
```

# Set the Data

In this simulation, we have 400 participants with 200 variables where 5 are important variables.

```{r}
#settings
n=n_sub=1000
p=200
beta0=rep(1,7)
p0=length(beta0)
beta = c(beta0,rep(0,p-p0))
n_obs<-rep(1,n_sub)

ka = 0
rho=0.6
type="cs"
dis="normal"
n_sim = 1
#Please note that n_sim=2 is just for quick demo


```

# Simulate one iteration of data for illustration

```{r}
    #generate errors for each subject
    e = NULL
    id<-NULL
    for (i in 1:n_sub){
      id<-c(id,rep(i,n_obs[i]))

    }

    #generate y and X
    N=sum(n_obs)
    nk=n_obs
    cn = c(0, cumsum(n_obs))
    x=X=matrix(rnorm(N*p),N,p)
    e=rnorm(N,0,.5)
    y=X%*%beta+(1+ka*abs(X[,1]))*e
    sim_data<-data.frame(y,x)

#write.csv(sim_data,"sim_data.csv",row.names = F )

```


```{r}
y = sim_data$y
X = as.matrix(sim_data%>% select(-y))

tau_list <- c(0.1,0.5,0.9)
sim=1
PQGEE_results <- NULL
final_results <- matrix(NA,ncol=21,nrow=6)
for(tau in tau_list){#tau=0.1
  

    #non-longitudinal quantile regression as initial
    betaint=coefficients(rq(y~0+X,tau = tau))

    #Apply proposed method with hbic tuning
    for(structure in c("Ind")){
      PQGEE_results[[structure]][[sim]] <-  qlingee_scad_hbic(x,y,betaint,nk,structure,tau=tau, max_it=100)
    }


# compile results ------------------------------------
  final_results[c(2*which(tau==tau_list)-1,2*which(tau==tau_list)),] <- compile_result_one(PQGEE_results,cutoff = 0.1,beta,beta0,structure = "Ind")
 

 
 }


final_results <- final_results[,1:7]
final_results <- final_results[!rowSums(is.na(final_results)),]
colnames(final_results)=c(c("F1 score","TP","FP","TN", "FN","MSE","MAD"))
#only report F1 MSE and MAD
condensed<-final_results[,c(1,6,7)]
row.names(condensed) <- paste("tau =",tau_list)
 xtable::xtable(condensed,digits =4)


```


# Print results
```{r}
knitr::kable(final_results)

```

