---
title: "Simulation 1e: SIS High dim Generic Covariates and Heteroskedasticity with SIS"
output:
  html_document:
    df_print: paged
---



```{r,warning=FALSE,message=FALSE}
if(!require(mvtnorm)){install.packages("mvtnorm");library(mvtnorm)}else{library(mvtnorm)}
if(!require(quantreg)){install.packages("quantreg");library(quantreg)}else{library(quantreg)}
if(!require(MASS)){install.packages("MASS");library(MASS)}else{library(MASS)}
if(!require(SIS)){install.packages("SIS");library(SIS)}else{library(SIS)}

if(!require(foreach)){install.packages("foreach");library(foreach)}else{library(foreach)}
#self-made functions
source("./functions/qsicm.R")
source("./functions/plrq.R")
source("./functions/utils.R")
```

# Set the Data

In this simulation, we have 400 participants with 1000 variables where 5 are important variables.

```{r}
#settings
n=n_sub=400
p=1000
beta0=rep(1,7)
p0=length(beta0)
beta = c(beta0,rep(0,p-p0))
n_obs<-rep(10,n_sub);

ka = 1
rho=0.6
type="ar"
dis="normal"
n_sim = 100
#Please note that n_sim=2 is just for quick demo


```

# Simulate the Data

```{r}
tau_list <- c(0.1,0.5,0.9)
final_results_sim <- matrix(NA,ncol=15,nrow=6)
start_time = Sys.time()

for(tau in tau_list){ #tau= 0.1;sim=1
  PQGEE_results <- NULL
  SIS_results <- NULL
  for(sim in 1:n_sim){
    #print(paste0("simulation number is ",sim))
    #generate errors for each subject
    e = NULL
    id<-NULL
    for (i in 1:n_sub){
      id<-c(id,rep(i,n_obs[i]))
      sigmai=Siga_cov(rho,type,n_obs[i])
      if (dis=="normal") ei=rmvnorm(1, mean=rep(0, n_obs[i]), sigma=sigmai)
      if (dis=="t") ei=rmvt(1, sigmai, df = 4, delta = rep(0, n_obs[i]))
      e=c(e,ei);
    }

    #generate y and X
    N=sum(n_obs)
    nk=n_obs
    cn = c(0, cumsum(n_obs))
    x=X=matrix(rnorm(N*p),N,p)
    y=X%*%beta+(1+ka*abs(X[,1]))*e

    
  ####implement SIS for dimension reduction
        #screening by SIS
    SIS_result <- SIS(x,y,iter=TRUE,greedy=FALSE,nsis=200)
    selected_X <- SIS_result$sis.ix
    
    true_selected_vars<-which(abs(beta)>0)

    ##check to see how well SIS performs
   not_contained<-true_selected_vars[!(true_selected_vars %in% selected_X)]
    
   length(true_selected_vars)
   length(not_contained)
  
    SIS_results[[sim]] <- selected_X

    #keep screened X
    x=X[,selected_X]
    
    #non-longitudinal quantile regression as initial
    betaint=coefficients(rq(y~0+x,tau = tau))

    #Apply proposed method with hbic tuning
    for(structure in c("Ind","CS","AR")){
      PQGEE_results[[structure]][[sim]] <-  qlingee_scad_hbic(x,y,betaint,nk,
                                                         structure,tau=tau, max_it=100)
    }
}
# compile results ------------------------------------
  final_results_sim[c(2*which(tau==tau_list)-1,2*which(tau==tau_list)),] <- #compile_result(PQGEE_results,n_sim,cutoff = 0.1,beta,beta0)
compile_result_hd(PQGEE_results,SIS_results,n_sim,cutoff = 0.1,beta,beta0,p)
}

end_time = Sys.time()
total_time=end_time - start_time
```


# Print results
```{r}



xtable::xtable(final_results_sim,
               digits=c(1,rep(c(2,2,2,4,4),3)))

knitr::kable(final_results)
```

